### ISSUE TITLE
no-relation class

### ISSUE THREAD

**Issue by SalvatoreHe** [lorjul/fair-psgg#4]
I am very interested in your work. Could you please explain the motivation behind the "no-relation" class and how it benefits from previous top-k retrieval models?

**Comment by SalvatoreHe** [comment]
Thanks for your reply. Yes, I understand what you are saying (as stated in the paper). What I am curious about is the advantage of selecting the top-k no-relation class scores that are the lowest before performing the relation prediction versus performing the top-k relation predictions directly (using triplet scores directly, e.g., subject score*object score*relation score) in previous work?

**Comment by lorjul** [comment]
I see, my bad.

The intuition behind our approach was that learning the no-relation class is easier than learning accurate predicate scores because it is a simpler task. That's why we preferred to split relation selection into
1. relation ranking (using the no-relation score) and then
2. predicate selection (using the remaining scores).

If the model is now very sure that there must be a relation between the given pair, but all the remaining predicate scores are rather low, we trust the relation ranking output more because it is the easier task. We can then use argmax over the predicate scores even though they are quite low because we are only interested which predicate is most likely, given a relation is present.

If there are still some open questions, I'm happy to help.

**Comment by SalvatoreHe** [comment]
> I see, my bad.
> 
> The intuition behind our approach was that learning the no-relation class is easier than learning accurate predicate scores because it is a simpler task. That's why we preferred to split relation selection into
> 
> 1. relation ranking (using the no-relation score) and then
> 2. predicate selection (using the remaining scores).
> 
> If the model is now very sure that there must be a relation between the given pair, but all the remaining predicate scores are rather low, we trust the relation ranking output more because it is the easier task. We can then use argmax over the predicate scores even though they are quite low because we are only interested which predicate is most likely, given a relation is present.
> 
> If there are still some open questions, I'm happy to help.

Thank you so much for your reply, I get what you mean!
